img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 128
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: False  # Conditioning with DECA
  hadamart_prep: "Tanh"

param_model:
  params_selector: []

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip']
  in_channels: 3
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null]

relighting:
  use_SH: False

dataset:
  deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"
  laplacian_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/laplacian/"
  laplacian_mask_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/eyes_segment/"

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 10000

train_misc:
  exp_name: "Brightness_Exp"
  cfg_name: "Masked_Face_woclip_no_nonspatial"