diffusion:
  predict_xstart: False
  denoise_src: False

img_model:
  name: "ImgCond"
  arch: "UNetCond_No_DPM_NoTime"
  image_size: 128
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['src_light', 'dst_light', 'shadow']

img_cond_model:
  apply: False

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 10000
  save_interval: 20000

dataset:
  training_data: "generated_dataset_80perc"
  deca_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/params/"
  data_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/gen_images/"
  face_segment_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/rendered_images/"


train_misc:
  exp_name: "paired_training"
  cfg_name: "paired+allunet_eps+src_dst_light+nodpm_128"