img_model:
  name: "ImgCond"
  arch: "UNetCond"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with params
  condition_proj_dim: 512

img_cond_model:
  arch: "EncoderUNet"
  in_image: 'raw'
  in_channels: 3
  image_size: 64

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'light', 'faceemb', 'img_latent']

dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"
