img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 64
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['light']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['normal_map']
  in_channels: 3
  image_size: 64
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null]
  noise_dpm_cond_img: [Null]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 25000

dataset:
  root_path: "/data/mint/Aom_Dataset/"
  training_data: "scene2"

train_misc:
  exp_name: "Test_Conditioning"
  cfg_name: "scene_normal_64"