img_model:
  name: "ImgCond"
  arch: "ControlledUnetModel_DPPNonSpa"
  image_size: 128
  in_image: ['raw']
  num_heads: 8
  num_res_blocks: 2
  in_channels: 3
  num_channels: 256
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  attention_resolutions: "4,2,1"

img_cond_model:
  apply: False 
  arch: "ControlNet"
  in_image: ['deca_masked_face_images_woclip', 'shadow_diff_with_weight_simplified', 'face_structure']
  in_channels: 5
  image_size: 128
  num_heads: 8
  num_res_blocks: 2
  num_channels: 256
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null, Null]
  noise_dpm_cond_img: [Null, Null, Null]
  canny_thres: [Null, Null, Null]
  attention_resolutions: "4,2,1"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

relighting:
  use_SH: False

conditioning:
  face_structure:
    parts: ['hair', 'faceskin', 'eyes', 'pupils', 'glasses', 'ears', 'nose', 'inmouth', 'u_lip', 'l_lip', 'neck', 'cloth', 'hat', 'bg']

train:
  weight_decay: 0.0
  sampling_interval: 100000
  save_interval: 50000
  use_prep_data: False
  lr: 1e-5

dataset:
  deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment_with_pupil/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"
  shadow_diff_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/shadow_diff_SS_with_c_simplified/"

train_misc:
  exp_name: "ControlNet"
  cfg_name: "CTRL_spa+DPP_nonspa"