img_model:
  name: "DecaCond"
  arch: "EncoderUNet"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 2048 # Output channels of encoderUNet
  condition_dim: 159  # It's the numbers of deca
  num_head_channels: 64
  attention_resolutions: "\"32, 16, 8\""
  use_scale_shift_norm: True
  resblock_updown: True
  num_res_blocks: 2
  num_channels: 128


param_model:
  name: "DecaCond"
  deca_cond: True
  conditioning: True


dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"

