img_model:
  name: "DecaCond"
  arch: "EncoderUNet"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 2048 # Output channels from encoderUNet
  condition_dim: 159  # It's the numbers of deca

param_model:
  name: "DecaCond"
  deca_cond: True
  conditioning: True


dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"

