img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 32
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 8
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb', 'shadow']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'canny_edge_bg']
  in_channels: 4
  image_size: 32
  out_channels: 32
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, dilate=5]
  noise_dpm_cond_img: [Null, Null]
  canny_thres: [Null, [51, 204]]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 25000

dataset:
  deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"


train_misc:
  exp_name: "Changing_BG"
  cfg_name: "difareli_canny=51to204bg_128"