img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['raw', 'face', 'deca']
  in_channels: 3
  image_size: 64
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  pool: 'adaptivenonzero'
  prep_image: [Null]
  # resblock_updown: True
  resblock_updown: False
  num_head_channels: -1

relighting:
  use_SH: False

dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train/"
  face_segment_dir: "/data/mint/ffhq_256_with_anno/face_segment/train/anno/"
  deca_shading_dir: "/data/mint/ffhq_256_with_anno/shading_images/train/"


train_misc:
  exp_name: "EncLight_SpatialCondition"
  cfg_name: "UNetCond_SpatialCondition"