img_model:
  name: "ImgCond"
  arch: "UNetCond"
  image_size: 128
  in_image: ['raw']
  prep_in_image: [Null]
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  apply_dpm_cond_img: False 

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'light', 'faceemb', 'shadow']

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 10000

train_misc:
  exp_name: "ConditionAblation"
  cfg_name: "DiffAE+shadow"

