img_model:
  name: "ImgCond"
  arch: "UNetCond"
  image_size: 128
  in_image: 'raw' 
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'light', 'img_latent', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet"
  in_image: ['faceseg_bg_noface&nohair']
  in_channels: 3
  image_size: 128
  out_channels: 128
  condition_dim: 128
  override_cond: 'img_latent'
  pool: 'adaptivenonzero'
  prep_image: [Null]
  noise_dpm_cond_img: [Null]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 10000

train_misc:
  exp_name: "AddingBG"
  cfg_name: "Enc_Bg_Latent"


