diffusion:
  predict_xstart: False
  denoise_src: False

img_model:
  name: "ImgCond"
  arch: "UNetCond_No_DPM_NoTime"
  image_size: 128
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb', 'shadow', 'src_light', 'dst_light']

img_cond_model:
  apply: False

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 20000
  save_interval: 20000

dataset:
  training_data: "Generated_Dataset_TargetLight/Generated_Dataset/"
  deca_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset/params_recreate/"
  data_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset/images/"
  face_segment_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset/rendered_images/"


train_misc:
  exp_name: "TPAMI_conditioning_ablation"
  cfg_name: "paired+nonspa+nobg+nodpm+trainset_128"