img_model:
  name: "ImgCond"
  arch: "UNetCond"
  image_size: 128
  in_image: 'raw' 
  in_channels: 9
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  # Image-Condition directly to UNet(DPM)
  dpm_cond_img: ['deca_masked_face_images_woclip', 'faceseg_nohead']
  prep_dpm_cond_img: [Null, Null]
  noise_dpm_cond_img: [Null, 'sep-dpm_noise']
  apply_dpm_cond_img: True

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: False

relighting:
  use_SH: False

train_misc:
  exp_name: "Retraining_BG"
  cfg_name: "All_in_UNet"