#!/bin/bash
cd ../../
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 10 13 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 15 16 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 22 23 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 24 25 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 26 30 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 34 36 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 41 43 --save_vid --postfix bd_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/bd_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 1 --lerp --idx 44 50 --save_vid --postfix bd_images
