#!/bin/bash
cd ../../
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 15 16 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 19 20 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 23 25 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 27 30 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 31 33 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 35 36 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 37 38 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 39 40 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 41 42 --save_vid --postfix rc_images && wait &&
python relight_idx_debugging.py --dataset debugging_ffhq --sub_dataset itw_images/replace_bg/rc_images --set valid --step 085000 --out_dir /data/mint/sampling/debugging_ITW_replacebg --cfg_name Masked_Face_woclip+BgNoHead+shadow_256.yaml --log_dir Masked_Face_woclip+BgNoHead+shadow_256 --diffusion_steps 1000 --seed 47 --sample_pair_json /home/mint/guided-diffusion/experiment_scripts/ITW_debugging/debugging_img/itw_images/replace_bg/itw_replace_bg.json --sample_pair_mode pair --itp render_face --itp_step 2  --batch_size 2 --gpu_id 2 --lerp --idx 43 45 --save_vid --postfix rc_images