img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 128
  in_image: 'raw' 
  in_channels: 6
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"
  # Image-Condition directly to UNet(DPM)
  dpm_cond_img: ['faceseg_bg_noface&nohair']
  prep_dpm_cond_img: [Null]
  noise_dpm_cond_img: [Null]
  apply_dpm_cond_img: True

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip']
  in_channels: 3
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null]
  noise_dpm_cond_img: [Null]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 10000

diffusion:
  predict_xstart: True

train_misc:
  exp_name: "Predict_x0"
  cfg_name: "Enc_Face+UNet_Bg"
