img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 64
  in_image: ['ldm_vq-f4']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb', 'shadow']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'faceseg_nohead']
  in_channels: 6
  image_size: 64
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null]
  noise_dpm_cond_img: [Null, Null]

train:
  sampling_interval: 25000
  save_interval: 5000

dataset:
  # deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  # data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  # face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment/"
  # deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"
  root_path: "/data/mint/DPM_Dataset/"
  training_data: "ffhq_256_with_anno"

train_misc:
  exp_name: "DiFaReli_LDM"
  cfg_name: "difareli_ldm_vq-f4_64"