diffusion:
  predict_xstart: False
  denoise_src: False

img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart_No_DPM_NoTime"
  image_size: 128
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb', 'shadow']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip']
  sj_paired: ['dst']
  in_channels: 3
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null]
  noise_dpm_cond_img: [Null]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 10000
  save_interval: 20000

dataset:
  training_data: "generated_dataset_80perc"
  deca_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/params/"
  data_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/gen_images/"
  face_segment_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/generated_dataset_80perc/rendered_images/"



train_misc:
  exp_name: "paired_training"
  cfg_name: "paired+allenc_eps+nobg+dst_shading+nodpm_128"