img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 128
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'faceseg_bg_noface&nohair', 'laplacian_topmost_eyes']
  in_channels: 9
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, 'dilate=5', 'dilate=5']

relighting:
  use_SH: False

dataset:
  deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"
  laplacian_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/laplacian/"
  laplacian_mask_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/eyes_segment/"


train_misc:
  exp_name: "EncLight_Masked_Rendered_Face"
  cfg_name: "UNetCond128_maksed_woclip_ears_dilate5"