img_model:
  name: "Img"
  arch: "UNetCond"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  condition_dim: 159  # It's the numbers of deca

dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"
