img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 256
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'shadow_diff_with_weight_onehot', 'canny_edge_bg']
  in_channels: 5
  image_size: 256
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null, dilate=5]
  noise_dpm_cond_img: [Null, Null, Null]
  canny_thres: [Null, Null, [153, 204]]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 200000
  save_interval: 005000
  use_prep_data: False

dataset:
  root_path: "/ist/ist-share/vision/mint/DPM_Dataset/"
  training_data: "ffhq_256_with_anno"
  deca_dir: "/ist/ist-share/vision/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/ist/ist-share/vision/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/ist/ist-share/vision/mint/DPM_Dataset//ffhq_256_with_anno/face_segment_with_pupil/"
  deca_rendered_dir: "/ist/ist-share/vision/mint/DPM_Dataset//ffhq_256_with_anno/rendered_images/"
  shadow_diff_dir: "/ist/ist-share/vision/mint/DPM_Dataset/ffhq_256_with_anno/shadow_diff_with_weight_onehot/"

train_misc:
  exp_name: "CastShadows"
  cfg_name: "DiFaReli_Canny_SdiffW_256_v100"