img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart_No_DPM"
  image_size: 128
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb', 'shadow']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'faceseg_nohead']
  in_channels: 6
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null]
  noise_dpm_cond_img: [Null, Null]

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 70000
  save_interval: 10000

dataset:
  deca_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/ffhq_256/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_256_with_anno/rendered_images/"

train_misc:
  exp_name: "No_Diffusion"
  cfg_name: "Ours_no_dpm_128"