img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart"
  image_size: 128
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'shadow_diff_with_weight_onehot', 'face_structure']
  in_channels: 5
  image_size: 128
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null, Null]
  noise_dpm_cond_img: [Null, Null, Null]
  canny_thres: [Null, Null, Null]

relighting:
  use_SH: False

conditioning:
  face_structure:
    parts: ['hair', 'faceskin', 'eyes', 'pupils', 'glasses', 'ears', 'nose', 'inmouth', 'u_lip', 'l_lip', 'neck', 'cloth', 'hat']

train:
  weight_decay: 0.0
  sampling_interval: 100000
  save_interval: 100000
  use_prep_data: True

dataset:
  training_data: "ffhq_with_anno_preprocessed"
  deca_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/params/"
  data_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/ffhq_128/"
  face_segment_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/face_segment/"
  face_structure_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/face_segment_onehot/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/rendered_images/"
  shadow_diff_dir: "/data/mint/DPM_Dataset/ffhq_with_anno_preprocessed/res128/shadow_diff_with_weight_onehot/"

train_misc:
  exp_name: "CastShadows"
  cfg_name: "DiFaReli_Fs_SdiffW_128_prep_VLL"