img_model:
  name: "ImgCond"
  arch: "UNetNormalsAll"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'light', 'faceemb']
  rmv_params: ['light']

relighting:
  reduce_shading: True
  arch: 'add_channels'
  mult_shaded: 'SharedConv'
  num_shaded_ch: 3

img_cond_model:
  apply: True
  arch: "EncoderUNet"
  in_image: 'raw'
  in_channels: 3
  image_size: 64
  out_channels: 27
  condition_dim: 27
  pool: 'spatial'
  override_cond: "light"

dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"
