diffusion:
  predict_xstart: False
  denoise_src: False

img_model:
  name: "ImgCond"
  arch: "UNetCond_SpatialCondition_Hadamart_No_DPM_NoTime"
  image_size: 256
  in_image: ['raw']
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512
  hadamart_prep: "Tanh"

img_cond_model:
  apply: True
  arch: "EncoderUNet_SpatialCondition"
  in_image: ['deca_masked_face_images_woclip', 'deca_masked_face_images_woclip', 'shadow_diff_with_weight_simplified', 'shadow_diff_with_weight_simplified']
  sj_paired: ['src', 'dst', 'src', 'dst']
  in_channels: 6
  image_size: 256
  out_channels: 128
  condition_dim: 256
  override_cond: "spatial_latent"
  prep_image: [Null, Null, Null, Null]
  noise_dpm_cond_img: [Null, Null, Null, Null]

param_model:
  params_selector: ['shape', 'pose', 'exp', 'cam', 'faceemb']

relighting:
  use_SH: False

train:
  weight_decay: 0.0
  sampling_interval: 25000
  save_interval: 25000

dataset:
  training_data: "Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/"
  deca_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/params_recreate/"
  data_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/images/"
  face_segment_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/face_segment/"
  deca_rendered_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/rendered_images/"
  shadow_diff_dir: "/data/mint/DPM_Dataset/Generated_Dataset_TargetLight/Generated_Dataset_cast_shadows_extra_rotate/shadow_diff_SS_with_c_simplified_npy/"


train_misc:
  exp_name: "TPAMI_main_results"
  cfg_name: "difareli++_finetune_rotate_256"