img_model:
  name: "ImgCond"
  arch: "UNetCond"
  image_size: 64
  in_image: 'raw'
  in_channels: 3
  out_channels: 3
  conditioning: True  # Conditioning with DECA
  condition_proj_dim: 512

param_model:
  params_selector: ['faceemb']

dataset:
  deca_dir: "/data/mint/ffhq_256_with_anno"
  data_dir: "/data/mint/ffhq_256_with_anno/ffhq_256/train"
